// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
// See the LICENSE file in the project root for more information.
using System;
using System.Collections;
using System.Collections.Generic;

public class Test<TKey, TValue>
{
    public void TestFunction()
    {
        foreach (KeyValuePair<TKey, TValue> item in new List<KeyValuePair<TKey, TValue>>());
        {
            Console.WriteLine();
        }
    }
}

public class Test24523
{
    // This test verifies that a proper ELEMENT_TYPE_MODULE_ZAPSIG element is generated by crossgen 
    // with large version bubble enabled for a constraint type in case constraint is in a module 
    // different from the module of the target method.
    public static int Main()
    {
        var test = new Test<int, int>();
        test.TestFunction();
        return 100;
    }
}
